# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dae2f30bc213ba3e12ecb9586449609cb23e4c9c8d36f55ff7b2279f8826400fa9e451480f7b318636b31df75e6e740aaa0f10b0c3ffb2eed27dc78445062bf

test:
  secret_key_base: 43224d487f42bebc1da32c4bdb4c44f3ebe428074e029cdfa48e60db51a2432a0fce4b1e37ba9d57740134652d45a9e108289b70c1c4486416fc203b41a90113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
